### ISSUE TITLE
ViewPublicProfile hardcodejat

### ISSUE THREAD

**Issue by marianievas** [OFF-Home/off-home-app#88]

**Comment by Ferran00** [comment]
si per la app final ho treiem, no cal arreglar-ho.
Perquè arreglar-ho no és simplement passar dades, també implica crear un atrib de les dades de l'usuari actual, comprovar si es null o no (per a l'estona fins q es reben les dades), ...

**Comment by marianievas** [comment]
Em sembla bé, ho deixem estar.
